import type { Metadata } from "next";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokBridgeLoader from "@storyblok/react/bridge-loader";

import Page from "@/storyblok/components/Page";
import Teaser from "@/storyblok/components/Teaser";
import Grid from "@/storyblok/components/Grid";
import Feature from "@/storyblok/components/Feature";
import Hero from "@/storyblok/components/Hero";

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/storyblok/components/Header";
import FeatureCardSection from "@/storyblok/components/FeatureCardSection";
import FaqSection from "@/storyblok/components/FaqSection";
import InternalLinkSection from "@/storyblok/components/InternalLinkSection";
import Footer from "@/storyblok/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: process.env.SB_ACCESS_TOKEN,
  use: [apiPlugin],
  components: {
    teaser: Teaser,
    page: Page,
    grid: Grid,
    feature: Feature,
    hero: Hero,
    header: Header,
    feature_card_section: FeatureCardSection,
    faq_section: FaqSection,
    internal_link_section: InternalLinkSection,
    footer: Footer,
  },
  apiOptions: {
    region: "eu",
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* for Storyblok visual editor with React server components */}
      <StoryblokBridgeLoader options={{}} />
    </html>
  );
}
